name: Node CI

on: [push]
  branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
       env:
        GITHUB_TOKEN: ${{ secrets.github_action_token }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm build 
        cp ./google*.html ./docs
        git init
        git remote add origin https://hidekuma:$GITHUB_TOKEN@github.com/HiDIKI/hidiki.github.io.git
        git config user.name hidekuma
        git config user.email d.hidekuma@gmail.com
        git add -A
        git commit -m "DEPLOY"
        git push -f --set-upstream origin master
      env:
        CI: true
