name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.github_action_token }}
        GITHUB_USER_NAME: ${{ secrets.user_name }}
        GITHUB_USER_EMAIL: ${{ secrets.user_email }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm install
        git clone https://$GITHUB_USER_NAME:$GITHUB_TOKEN@github.com/HiDIKI/hidiki.github.io.git docs
        npm run build
        cp ./google*.html ./docs
        cd ./docs
        git config user.name $GITHUB_USER_NAME
        git config user.email $GITHUB_USER_EMAIL
        git add -A
        git commit -m "DEPLOY"
        git push --set-upstream origin master
      env:
        CI: true
